const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const root = path.resolve(__dirname, '..');
const target = path.resolve(root, '../supabase/functions/chekmi-verify/index.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
esbuild.buildSync({
  stdin: { contents: 'import { createEdgeVerificationHandler } from "./src/edgeVerification";\nDeno.serve(createEdgeVerificationHandler(Deno.env.toObject()));', resolveDir: root, loader: 'ts' },
  bundle: true, platform: 'browser', format: 'esm', target: 'es2022', outfile: target,
  banner: { js: '// Generated by backend-server/scripts/build-edge.cjs. Edit src/edgeVerification.ts and rebuild.\n// Deploy with verify_jwt=false: this handler validates Chekmi staff sessions through its trusted database RPC.' },
});
const code = fs.readFileSync(target, 'utf8');
if (/sk_live_[a-z0-9]{20,}|require\(|\bfrom\s+["']|process\.env|aletcloud\.com/i.test(code)) throw Error('Unexpected secret, Node dependency, or Alet reference in Edge bundle');
console.log('Bundled standalone Supabase verification function:', target, fs.statSync(target).size, 'bytes');
