// Generated by backend-server/scripts/build-edge.cjs. Edit src/edgeVerification.ts and rebuild.
// Deploy with verify_jwt=false: this handler validates Chekmi staff sessions through its trusted database RPC.

// src/receiptFormat.ts
function nonEmpty(value) {
  const text = String(value ?? "").replace(/\s+/g, " ").trim();
  return text ? text : null;
}
function ethiopianLocalDate(value) {
  const text = nonEmpty(value);
  if (!text) return null;
  let match = text.match(
    /^(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2})(?::(\d{2}))?$/
  );
  if (match) {
    const [, day, month, year, hour, minute, second = "00"] = match;
    return validIso(`${year}-${month}-${day}T${hour}:${minute}:${second}+03:00`);
  }
  match = text.match(
    /^(\d{4})[-/](\d{1,2})[-/](\d{1,2})[, ]+\s*(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?$/i
  );
  if (match) {
    const [, year, month, day, rawHour, minute, second = "00", meridiem] = match;
    let hour = Number(rawHour);
    if (meridiem) {
      hour %= 12;
      if (meridiem.toUpperCase() === "PM") hour += 12;
    }
    return validIso(
      `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}T${String(hour).padStart(2, "0")}:${minute}:${second}+03:00`
    );
  }
  match = text.match(
    /^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?$/
  );
  if (match) {
    const [, year, month, day, hour, minute, second = "00"] = match;
    return validIso(`${year}-${month}-${day}T${hour}:${minute}:${second}+03:00`);
  }
  return validIso(text);
}
function validIso(value) {
  const date = new Date(value);
  return Number.isNaN(date.valueOf()) ? null : date.toISOString();
}
function completedStatus(value) {
  const normalized = String(value ?? "").toLowerCase().replace(/[^a-z]+/g, " ").trim();
  return (/* @__PURE__ */ new Set([
    "success",
    "successful",
    "completed",
    "complete",
    "settled",
    "paid",
    "transaction successful",
    "transaction completed",
    "transaction completed successfully",
    "payment successful",
    "payment completed"
  ])).has(normalized);
}
function referencesMatch(left, right) {
  const normalize = (value) => String(value ?? "").toUpperCase().replace(/[^A-Z0-9]/g, "");
  const normalizedLeft = normalize(left);
  const normalizedRight = normalize(right);
  return Boolean(normalizedLeft && normalizedLeft === normalizedRight);
}
function safeRaw(raw) {
  const copy = { ...raw };
  delete copy.base64Data;
  delete copy.pdf;
  return copy;
}
var LEGACY_REFERENCE = /^FT[A-Z0-9]{10}$/i;
var LEGACY_COMBINED_ID = /^(FT[A-Z0-9]{10})(\d{8})$/i;
var NEW_CBE_URL = /^https?:\/\/mbreciept\.cbe\.com\.et\/([A-Za-z0-9-]+)\/?$/i;
var NEW_CBE_TOKEN = /^[A-Za-z0-9-]{15,80}$/;
function extractNewCbeToken(input) {
  const trimmed = input.trim();
  const urlMatch = trimmed.match(NEW_CBE_URL);
  if (urlMatch) return urlMatch[1] ?? null;
  if (!trimmed.toUpperCase().startsWith("FT") && NEW_CBE_TOKEN.test(trimmed)) {
    return trimmed;
  }
  return null;
}
function isLegacyCbeReference(input) {
  return LEGACY_REFERENCE.test(input.trim());
}
function extractLegacyCbeUrlData(input) {
  try {
    const url = new URL(input.trim());
    if (url.hostname.toLowerCase() !== "apps.cbe.com.et") return null;
    if (url.port && url.port !== "100") return null;
    const match = url.searchParams.get("id")?.trim().match(LEGACY_COMBINED_ID);
    if (!match) return null;
    return { reference: (match[1] ?? "").toUpperCase(), suffix: match[2] ?? "" };
  } catch {
    return null;
  }
}

// src/veritasProtocol.ts
var object = (value) => value !== null && typeof value === "object" && !Array.isArray(value) ? value : null;
function veritasRequest(provider, input) {
  let reference = (input.reference ?? input.receiptNumber ?? "").trim();
  if (provider === "cbe") reference = extractLegacyCbeUrlData(reference)?.reference ?? reference;
  if (provider !== "cbe" || !extractNewCbeToken(reference)) reference = reference.toUpperCase();
  const body = provider === "cbebirr" ? { receiptNumber: reference, phoneNumber: (input.phoneNumber ?? "").replace(/[\s()+-]/g, "").replace(/^0/, "251") } : { reference };
  if (provider === "cbe" && input.suffix) body.accountSuffix = input.suffix;
  if (provider === "abyssinia") body.suffix = input.suffix ?? "";
  return { path: `/verify-${provider}`, body, reference };
}
function field(raw, ...keys) {
  for (const key of keys) if (raw[key] !== null && raw[key] !== void 0) return raw[key];
  return null;
}
function money(value) {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value !== "string") return null;
  const text = value.trim().replace(/^(?:ETB|Birr)\s*/i, "").replace(/\s*(?:ETB|Birr)$/i, "").trim();
  if (!/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d{1,2})?$/.test(text)) return null;
  const amount = Number(text.replace(/,/g, ""));
  return Number.isFinite(amount) ? amount : null;
}
function normalizeVeritas(provider, submitted, payload) {
  const fail = (error) => ({ ok: false, provider, error, code: "NOT_VERIFIED" });
  let raw = object(payload);
  if (!raw) return fail("Veritas returned an invalid receipt response.");
  let explicitSuccess = false;
  for (let depth = 0; depth < 4; depth++) {
    if (raw.success === false || raw.verified === false || raw.ok === false || raw.error) {
      return fail("Veritas could not verify this transaction. Check the reference and provider.");
    }
    explicitSuccess ||= raw.success === true || raw.verified === true;
    const nested = object(raw.data);
    if (!nested) break;
    raw = nested;
  }
  const header = object(raw.header);
  if (header) {
    if (!completedStatus(header.status)) return fail("Veritas returned an unsuccessful bank response.");
    const row = Array.isArray(raw.body) ? object(raw.body[0]) : null;
    if (!row) return fail("Veritas returned no receipt details.");
    raw = row;
    explicitSuccess = true;
  }
  const reference = nonEmpty(provider === "cbebirr" ? raw.receiptNumber : provider === "mpesa" ? field(raw, "transactionId", "receiptNo", "receiptNumber") : field(raw, "reference", "receiptNo", "receiptNumber", "transactionReference", "id", "Transaction Reference", "Payment Reference"));
  const amount = money(field(raw, "settledAmount", "transferredAmount", "transactionAmount", "amountCredited", "amount", "Transferred Amount"));
  const dateTimes = Array.isArray(raw.dateTimes) ? raw.dateTimes : [];
  const txnDate = ethiopianLocalDate(field(raw, "txnDate", "paymentDate", "transactionDate", "date", "Transaction Date") ?? dateTimes[0]);
  const status = nonEmpty(field(raw, "transactionStatus", "status", "statusText"));
  if (status && !completedStatus(status) || provider === "telebirr" && !completedStatus(status)) {
    return fail("The provider has not confirmed a completed payment.");
  }
  if (!explicitSuccess && !completedStatus(status)) return fail("Veritas did not confirm verification.");
  const lookupReference = provider === "cbe" ? extractLegacyCbeUrlData(submitted)?.reference ?? submitted : submitted;
  const matchesReference = referencesMatch(lookupReference, reference) || provider === "mpesa" && referencesMatch(lookupReference, raw.receiptNo);
  if (!reference || !(provider === "cbe" && extractNewCbeToken(lookupReference)) && !matchesReference) {
    return fail("The returned bank reference does not match this payment.");
  }
  if (amount === null || amount <= 0 || !txnDate) return fail("Veritas returned incomplete payment amount or date details.");
  const currency = nonEmpty(raw.currency)?.toUpperCase() ?? "ETB";
  if (currency !== "ETB" && currency !== "BIRR") return fail("This payment is not denominated in ETB.");
  return { ok: true, provider, data: {
    reference,
    amount,
    currency: "ETB",
    txnDate,
    status: "completed",
    statusText: status,
    receiverAccount: nonEmpty(field(raw, "receiverAccount", "receiverAccountNumber", "creditedPartyAccountNo", "creditAccount", "creditAccountNo", "phoneNo", "Receiver's Account", "Beneficiary Account")),
    receiverName: nonEmpty(field(raw, "receiverName", "receiver", "creditedPartyName", "creditAccountHolder", "Receiver's Name", "Beneficiary Name")),
    payerAccount: nonEmpty(field(raw, "payerAccount", "payerTelebirrNo", "senderAccountNumber", "senderAccount", "debitAccount", "debitAccountNo", "Source Account", "Payer's Account")),
    payerName: nonEmpty(field(raw, "payerName", "payer", "customerName", "senderName", "debitAccountHolder", "Payer's Name", "Source Account Name")),
    totalAmount: money(field(raw, "totalPaidAmount", "totalAmount", "total")),
    serviceFee: money(field(raw, "serviceFee", "serviceCharge")),
    raw: safeRaw(raw)
  } };
}

// src/paymentSecurity.ts
function normalizeAccount(value) {
  const normalized = String(value ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
  if (/^0[79]\d{8}$/.test(normalized)) return `251${normalized.slice(1)}`;
  if (/^[79]\d{8}$/.test(normalized)) return `251${normalized}`;
  return normalized;
}
function matchesReceivingAccount(configuredAccount, verifiedAccount, minimumStableCharacters = 6) {
  const configured = normalizeAccount(configuredAccount);
  const verified = normalizeAccount(verifiedAccount);
  if (configured.length < minimumStableCharacters || verified.length < minimumStableCharacters) return false;
  return configured === verified || configured.endsWith(verified) || verified.endsWith(configured);
}
function matchesTelebirrReceivingAccount(configuredAccount, verifiedAccount) {
  const raw = String(verifiedAccount ?? "").trim().replace(/[\s()+-]/g, "");
  if (!raw.includes("*")) return matchesReceivingAccount(configuredAccount, verifiedAccount);
  const mask = /^251([79])\*{4}([0-9]{4})$/.exec(raw);
  const configured = authoritativeEthiopianPhone(configuredAccount);
  return Boolean(mask && configured && configured.startsWith(`251${mask[1]}`) && configured.endsWith(mask[2]));
}
function matchesCbeReceivingAccount(configuredAccount, verifiedAccount) {
  const configured = normalizeAccount(configuredAccount);
  const rawVerified = String(verifiedAccount ?? "").toLowerCase().replace(/[^a-z0-9*]/g, "");
  if (!rawVerified.includes("*")) {
    return matchesReceivingAccount(configuredAccount, verifiedAccount);
  }
  const match = rawVerified.match(/^([a-z0-9])\*+([a-z0-9]{4})$/);
  if (!match || configured.length < 8) return false;
  return configured.startsWith(match[1] ?? "") && configured.endsWith(match[2] ?? "");
}
function authoritativeAccountSuffix(configuredAccount, length) {
  if (!Number.isInteger(length) || length <= 0) return null;
  const digits = String(configuredAccount ?? "").replace(/\D/g, "");
  return digits.length >= length ? digits.slice(-length) : null;
}
function authoritativeEthiopianPhone(configuredAccount) {
  const normalized = normalizeAccount(configuredAccount);
  return /^251[79]\d{8}$/.test(normalized) ? normalized : null;
}
function validateTransactionFreshness(providerDate, options = {}) {
  if (providerDate === null || providerDate === void 0 || String(providerDate).trim() === "") {
    return {
      ok: false,
      code: "TRANSACTION_DATE_MISSING",
      message: "The provider did not return a transaction date."
    };
  }
  const transactionDate = new Date(String(providerDate));
  if (Number.isNaN(transactionDate.valueOf())) {
    return {
      ok: false,
      code: "TRANSACTION_DATE_INVALID",
      message: "The provider returned an invalid transaction date."
    };
  }
  const now = options.now ?? /* @__PURE__ */ new Date();
  const maxAgeMinutes = options.maxAgeMinutes ?? 24 * 60;
  const maxFutureSkewMinutes = options.maxFutureSkewMinutes ?? 10;
  const ageMs = now.valueOf() - transactionDate.valueOf();
  if (ageMs > maxAgeMinutes * 6e4) {
    return {
      ok: false,
      code: "TRANSACTION_TOO_OLD",
      message: `The payment is older than the allowed ${maxAgeMinutes}-minute verification window.`
    };
  }
  if (ageMs < -maxFutureSkewMinutes * 6e4) {
    return {
      ok: false,
      code: "TRANSACTION_DATE_IN_FUTURE",
      message: "The provider transaction date is unexpectedly in the future."
    };
  }
  return { ok: true, transactionDate };
}
function positiveAmount(value) {
  const parsed = typeof value === "number" ? value : Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

// src/edgeVerification.ts
var providers = /* @__PURE__ */ new Set(["telebirr", "cbe", "cbebirr", "dashen", "abyssinia", "mpesa"]);
var Failure = class extends Error {
  constructor(code, message, status = 422, retryable = false) {
    super(message);
    this.code = code;
    this.status = status;
    this.retryable = retryable;
  }
};
function json(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value) ? value : null;
}
async function readJson(body, limit) {
  const reader = body.body?.getReader();
  if (!reader) return null;
  const chunks = [];
  let length = 0;
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    length += value.length;
    if (length > limit) {
      await reader.cancel();
      throw new Failure("RESPONSE_TOO_LARGE", "The request or service response was too large.", 413);
    }
    chunks.push(value);
  }
  const buffer = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    buffer.set(chunk, offset);
    offset += chunk.length;
  }
  try {
    return JSON.parse(new TextDecoder().decode(buffer));
  } catch {
    throw new Failure("INVALID_SERVICE_RESPONSE", "The payment service returned an invalid response.", 502, true);
  }
}
function createEdgeVerificationHandler(env, transport = fetch) {
  const limits = /* @__PURE__ */ new Map();
  const inFlight = /* @__PURE__ */ new Set();
  const configured = Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY && env.VERITAS_API_KEY?.trim());
  return async (req) => {
    const requestId = crypto.randomUUID();
    const origin = req.headers.get("origin");
    const allowedOrigins = (env.CORS_ALLOWED_ORIGINS || "").split(",").map((x) => x.trim());
    const originAllowed = !origin || allowedOrigins.includes(origin);
    const headers = { "Content-Type": "application/json", "Cache-Control": "no-store", "x-request-id": requestId };
    if (origin && originAllowed) {
      headers["Access-Control-Allow-Origin"] = origin;
      headers.Vary = "Origin";
      headers["Access-Control-Allow-Headers"] = "authorization, apikey, content-type, x-client-info";
      headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS";
    }
    const respond = (status, body) => new Response(JSON.stringify({ ...body, requestId }), { status, headers });
    if (!originAllowed) return respond(403, { success: false, code: "ORIGIN_NOT_ALLOWED", error: "This web origin is not configured." });
    if (req.method === "OPTIONS") return new Response(null, { status: 204, headers });
    if (req.method === "GET") return respond(configured ? 200 : 503, {
      status: configured ? "ready" : "not_ready",
      verifierMode: "live",
      verifier: { engine: "veritas", mode: "transaction-id", configured, imageVerification: false },
      service: "chekmi-verify",
      version: "2026-09-08.2"
    });
    if (req.method !== "POST") return respond(405, { success: false, code: "METHOD_NOT_ALLOWED", error: "Use POST." });
    const token = req.headers.get("authorization")?.replace(/^Bearer\s+/i, "").trim();
    if (!token || token.length < 32) return respond(401, { success: false, code: "SESSION_REQUIRED", error: "Sign in before verifying a payment." });
    if (!configured) return respond(503, { success: false, code: "VERITAS_NOT_CONFIGURED", error: "Payment verification is not configured. Ask the administrator to complete Supabase function setup." });
    const startedAt = Date.now();
    const deadline = AbortSignal.timeout(45e3);
    let context = null;
    let provider;
    let reference = "";
    let canonicalReference = "";
    let expected = null;
    let lockKey = null;
    const rpc = async (name, params, timeout = 8e3) => {
      let res;
      try {
        res = await transport(`${env.SUPABASE_URL.replace(/\/$/, "")}/rest/v1/rpc/${name}`, {
          method: "POST",
          headers: { apikey: env.SUPABASE_SERVICE_ROLE_KEY, Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify(params),
          redirect: "error",
          signal: AbortSignal.any([deadline, AbortSignal.timeout(timeout)])
        });
        const value = await readJson(res, 1e6);
        if (!res.ok) {
          const detail = json(value);
          const code = String(detail?.code ?? "DATABASE_ERROR");
          if (code === "28000" || res.status === 401) throw new Failure("SESSION_EXPIRED", "Your staff session expired. Sign in again.", 401);
          if (code === "23505") throw new Failure("DUPLICATE_PAYMENT", "This payment has already been verified.", 409);
          if (code === "42501") throw new Failure("ACCESS_DENIED", "This staff account is not allowed to verify payments.", 403);
          throw new Failure(code, String(detail?.message ?? "The payment database is unavailable."), res.status >= 500 ? 503 : 400, res.status >= 500);
        }
        return value;
      } catch (e) {
        if (e instanceof Failure) throw e;
        throw new Failure("DATABASE_UNAVAILABLE", "Could not confirm the saved payment. Check payment history before retrying.", 503, true);
      }
    };
    const find = () => rpc("find_committed_payment", { p_token: token, p_provider: provider, p_transaction_ref: canonicalReference || reference });
    try {
      const body = json(await readJson(req, 21e5));
      if (!body || typeof body.provider !== "string" || !providers.has(body.provider)) throw new Failure("INVALID_PROVIDER", "Select a payment provider.", 400);
      provider = body.provider;
      const inputReference = typeof body.reference === "string" ? body.reference.trim() : "";
      if (!inputReference || inputReference.length > 256) throw new Failure("INVALID_REFERENCE", "Enter the bank transaction reference.", 400);
      reference = provider === "cbe" ? extractLegacyCbeUrlData(inputReference)?.reference ?? inputReference : inputReference.toUpperCase();
      if (provider === "cbe" && !extractNewCbeToken(reference)) reference = reference.toUpperCase();
      const action = body.action ?? "verify";
      if (action !== "verify" && action !== "status") throw new Failure("INVALID_ACTION", "Unknown verification action.", 400);
      expected = positiveAmount(body.expectedAmount);
      const businessReference = typeof body.tableNumber === "string" ? body.tableNumber.trim() : "";
      if (action === "verify" && (expected === null || !businessReference || businessReference.length > 320)) throw new Failure("INVALID_PAYMENT", "Enter a positive amount due and business reference.", 400);
      const photo = body.receiptImageBase64;
      if (photo !== void 0 && (typeof photo !== "string" || !/^[A-Za-z0-9+/]*={0,2}$/.test(photo) || photo.length % 4 !== 0 || photo.length > 2e6)) throw new Failure("RECEIPT_TOO_LARGE", "The receipt image is invalid or exceeds 1.5 MB.", 413);
      context = json(await rpc("get_verification_context", { p_token: token, p_provider: provider }));
      if (!context || context.provider !== provider || !["waiter", "admin"].includes(String(context.role)) || !context.business_id || !context.receiving_account) throw new Failure("ACCESS_DENIED", "This account cannot verify payments for that business.", 403);
      const existing = json(await find());
      if (existing?.ticket_id) return respond(200, { success: true, data: { ...existing, recovered: true, alreadyVerified: true } });
      if (action === "status") return respond(200, { success: false, code: "NOT_COMMITTED", error: "No saved verified payment was found for this reference.", state: "not_confirmed" });
      const identity = `${context.business_id}:${context.staff_number}`;
      const now = Date.now();
      for (const [key, bucket2] of limits) if (bucket2.until <= now) limits.delete(key);
      const bucket = limits.get(identity) ?? { count: 0, until: now + 6e4 };
      bucket.count++;
      limits.set(identity, bucket);
      if (bucket.count > 20) throw new Failure("RATE_LIMIT", "Too many verification attempts. Wait a minute.", 429, true);
      lockKey = `${context.business_id}:${provider}:${reference}`;
      if (inFlight.has(lockKey)) {
        lockKey = null;
        throw new Failure("VERIFICATION_IN_PROGRESS", "This payment is being checked. Check its saved result shortly.", 409, true);
      }
      inFlight.add(lockKey);
      const account = String(context.receiving_account);
      const lookup = { reference };
      let suffixProof = false;
      if (provider === "cbe" || provider === "abyssinia") {
        const suffix = authoritativeAccountSuffix(account, provider === "cbe" ? 8 : 5);
        if (!suffix) throw new Failure("RECEIVING_ACCOUNT_INVALID", "Update this business's receiving account in Admin.");
        lookup.suffix = suffix;
        suffixProof = provider === "abyssinia" || isLegacyCbeReference(reference);
      } else if (provider === "cbebirr") {
        const phone = authoritativeEthiopianPhone(account);
        if (!phone) throw new Failure("RECEIVING_ACCOUNT_INVALID", "Configure a valid CBE Birr receiving phone in Admin.");
        lookup.phoneNumber = phone;
      }
      const outgoing = veritasRequest(provider, lookup);
      let upstream;
      let payload;
      for (let attempt = 1; attempt <= 2; attempt++) {
        const timeout = Math.min(2e4, 45e3 - (Date.now() - startedAt) - 1e4);
        if (timeout < 1e3) break;
        const attemptStart = Date.now();
        upstream = void 0;
        let failed = false;
        try {
          upstream = await transport(`https://verifyapi.leulzenebe.pro${outgoing.path}`, {
            method: "POST",
            headers: { "x-api-key": env.VERITAS_API_KEY.trim(), "Content-Type": "application/json", Accept: "application/json" },
            body: JSON.stringify(outgoing.body),
            redirect: "error",
            signal: AbortSignal.any([deadline, AbortSignal.timeout(timeout)])
          });
          if ([500, 502, 503, 504].includes(upstream.status)) {
            failed = true;
            await upstream.body?.cancel();
          } else if (upstream.ok) {
            payload = await readJson(upstream, 1e6);
          } else {
            await upstream.body?.cancel();
          }
        } catch {
          failed = true;
        }
        console.info(JSON.stringify({
          event: "veritas_lookup",
          requestId,
          provider,
          attempt,
          httpStatus: upstream?.status ?? null,
          elapsedMs: Date.now() - attemptStart,
          outcome: failed ? "transient_failure" : "response"
        }));
        if (!failed) break;
        upstream = void 0;
        if (attempt < 2 && !deadline.aborted) await new Promise((resolve) => setTimeout(resolve, 400));
      }
      if (!upstream) throw new Failure("VERITAS_UNAVAILABLE", "The payment provider did not respond after a second check. Keep this receipt and try again shortly; this attempt did not save a payment.", 503, true);
      if (upstream.status === 401 || upstream.status === 403) throw new Failure("VERITAS_ACCESS_DENIED", "The Veritas key or subscription access needs attention in Supabase function secrets.", 503);
      if (upstream.status === 402) throw new Failure("VERITAS_CREDITS_EXHAUSTED", "The Veritas verification credit balance is exhausted.", 503);
      if (upstream.status === 429) throw new Failure("VERITAS_RATE_LIMIT", "Veritas is rate limiting requests. Wait a minute.", 429, true);
      if (upstream.status >= 500) throw new Failure("VERITAS_UNAVAILABLE", "The payment provider is temporarily unavailable. Keep this receipt and try again shortly.", 503, true);
      if (!upstream.ok) throw new Failure("NOT_VERIFIED", "Veritas could not verify this reference.");
      const verified = normalizeVeritas(provider, reference, payload);
      if (!verified.ok) throw new Failure("NOT_VERIFIED", verified.error);
      const data = verified.data;
      if (data.amount + 1e-3 < expected) throw new Failure("UNDERPAID", `Payment is ${data.amount} ETB; amount due is ${expected} ETB.`);
      const destinationMatches = provider === "cbe" ? matchesCbeReceivingAccount(account, data.receiverAccount) : provider === "telebirr" ? matchesTelebirrReceivingAccount(account, data.receiverAccount) : matchesReceivingAccount(account, data.receiverAccount);
      const returned = String(data.receiverAccount ?? "");
      const fullReturned = returned && !returned.includes("*");
      if (!suffixProof && !destinationMatches || suffixProof && fullReturned && !destinationMatches) throw new Failure("DESTINATION_MISMATCH", "Payment was not sent to this business's configured account.");
      const freshness = validateTransactionFreshness(data.txnDate, { maxAgeMinutes: 1440 });
      if (!freshness.ok) throw new Failure(freshness.code, `${freshness.message} Receipt date: ${data.txnDate ?? "missing"}.`);
      canonicalReference = data.reference.toUpperCase();
      const committed = json(await rpc("commit_verified_payment", {
        p_token: token,
        p_provider: provider,
        p_transaction_ref: canonicalReference,
        p_table_number: businessReference,
        p_expected_amount: expected,
        p_verified_amount: data.amount,
        p_currency: data.currency,
        p_receiver_account: suffixProof ? account : data.receiverAccount,
        p_receiver_name: data.receiverName ?? null,
        p_payer_account: data.payerAccount ?? null,
        p_payer_name: data.payerName ?? null,
        p_provider_transaction_at: freshness.transactionDate.toISOString(),
        p_provider_status: data.status,
        p_provider_payload: { ...data, verificationRequest: { submittedReference: inputReference, engine: "veritas", host: "supabase-edge", method: "transaction-id" }, ...suffixProof ? { destinationProof: { method: "server_configured_account_suffix" } } : {} },
        p_receipt_image_base64: photo ?? null
      }));
      if (!committed?.ticket_id) throw new Failure("COMMIT_NOT_CONFIRMED", "No saved payment confirmation was returned. Check payment history before retrying.", 503, true);
      return respond(201, { success: true, data: { ...committed, amount: data.amount, expectedAmount: expected, tipAmount: Math.max(0, data.amount - expected), currency: data.currency } });
    } catch (error) {
      const failure = error instanceof Failure ? error : new Failure("VERIFICATION_UNAVAILABLE", "Payment verification could not finish. Check payment history before retrying.", 503, true);
      if (failure.code === "DUPLICATE_PAYMENT") {
        try {
          const existing = json(await find());
          if (existing?.ticket_id) return respond(200, { success: true, data: { ...existing, recovered: true, alreadyVerified: true } });
        } catch {
        }
      }
      if (context && provider && failure.status === 422) {
        try {
          await rpc("service_record_failed_verification", { p_token: token, p_provider: provider, p_transaction_ref: reference, p_expected_amount: expected, p_verified_amount: null, p_error_code: failure.code, p_error_message: failure.message }, 2e3);
        } catch {
        }
      }
      return respond(failure.status, { success: false, code: failure.code, error: failure.message, retryable: failure.retryable, ...failure.retryable ? { retryAfterSeconds: 60 } : {} });
    } finally {
      if (lockKey) inFlight.delete(lockKey);
    }
  };
}

// <stdin>
Deno.serve(createEdgeVerificationHandler(Deno.env.toObject()));
